### PR TITLE
Feat blueprint

### PR DESCRIPTION
**Pull request by mixcas**

### CODE REVIEW

**Comment by varffs** [comment]
screen shot 2016-11-21 at 12 54 55

Does this ^ matter? Do you get this error too?

**Comment by varffs** [comment]
Should you also be doing the login/logout/accounts-ui stuff in this branch?

**Comment by mixcas** [comment]
@varffs idk if it matters, is blueprint working?

**Comment by mixcas** [comment]
@varffs i think login/logout/accounts should be done in a diff branch

**Pull request merged**
